name: cat_or_dog
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+2

  image: ^3.3.0
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0 
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/images/cat.png
    - assets/images/dog.png